export default function TermsAndConditions() {
  return (
    <div className="px-8">
      <h1 className="text-3xl font-bold text-pink-700 mb-6">Terms &amp; Conditions</h1>
      <h2 className="text-lg font-semibold mb-4">WOMEN, CHILD &amp; HUMAN RIGHTS TRUST (WCRT.IN)</h2>
      <p className="mb-2 text-sm text-gray-600">Effective Date: 01/07/2023 - V1.12</p>
      <section className="mb-4">
        <h3 className="font-bold">A. Electronic Record and Acceptance</h3>
        <p className="mb-2">This document is an electronic record in terms of the Information Technology Act, 2000 and relevant rules thereunder. It is generated by a computer system and does not require any physical or digital signatures.</p>
        <h3 className="font-bold">B. Website Disclosure</h3>
        <p className="mb-2">This document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, requiring the publication of the rules, regulations, privacy policy and terms of use for access to or use of the domain name wcrt.in (“Website”), including the associated mobile site and mobile application (“Platform”).</p>
        <h3 className="font-bold">C. Organization Information</h3>
        <p className="mb-2">The Platform is owned and operated by Women, Child &amp; Human Rights Trust (WCRT), a non-governmental organization dedicated to advancing the rights and welfare of women and children. Registered Address: A-116/19, Street 44, Gamri, Sombazar, Delhi, New Delhi, India. Hereinafter referred to as the “Trust,” “we,” “us,” or “our.”</p>
        <h3 className="font-bold">D. Scope and Acceptance</h3>
        <p className="mb-2">By accessing or using this Platform and our services (including making donations, purchasing fundraising items, or engaging with our content), you expressly acknowledge, understand, and agree to be bound by these Terms and Conditions (“Terms of Use”), as may be amended from time to time. If you do not agree to these terms, please do not use this Platform.</p>
      </section>
      <hr className="my-6" />
      <ol className="list-decimal pl-6 space-y-4 mb-4">
        <li>
          <strong>Eligibility and Registration</strong>
          <ul className="list-disc pl-6 mt-1">
            <li>You may be required to provide true, accurate, and complete information during registration or when donating/purchasing. You are solely responsible for maintaining the confidentiality of your account and for all activities that occur under your account.</li>
          </ul>
        </li>
        <li>
          <strong>No Warranties; Limitation of Liability</strong>
          <ul className="list-disc pl-6 mt-1">
            <li>The information, materials, goods, and services provided on this Platform are on an “as is” and “as available” basis. We make no warranties of any kind, express or implied, regarding the accuracy, completeness, reliability, suitability, or availability of the Platform or the information, products, services, or related graphics contained on the Platform for any purpose.</li>
            <li>Your use of the Platform and services is at your own risk. In no event shall the Trust be liable for any loss or damage, including indirect or consequential loss or damage, arising out of, or in connection with, the use of this Platform.</li>
          </ul>
        </li>
        <li>
          <strong>Intellectual Property</strong>
          <ul className="list-disc pl-6 mt-1">
            <li>All content, including but not limited to text, images, graphics, logos, and layouts, are the sole property of WCRT or are licensed for use by the Trust. Unauthorized use or reproduction is strictly prohibited.</li>
          </ul>
        </li>
        <li>
          <strong>Prohibited Uses</strong>
          <ul className="list-disc pl-6 mt-1">
            <li>You shall not use the Platform for any purpose that is unlawful, prohibited by these terms, or inconsistent with the mission of WCRT or in violation of any applicable laws or regulations.</li>
          </ul>
        </li>
        <li>
          <strong>Donation and Fundraising Sales</strong>
          <ul className="list-disc pl-6 mt-1">
            <li>All donations made via the Platform are voluntary, non-refundable, and non-transferable. Receipts will be issued as per applicable laws.</li>
            <li>Items such as plants, fixtures, and paintings offered for sale through the Platform are part of WCRT’s fundraising initiatives. Such sales are non-refundable and are treated as contributions to the NGO’s objectives.</li>
            <li>We reserve the right to refuse or cancel any donation or purchase at our sole discretion.</li>
          </ul>
        </li>
        <li>
          <strong>Payment Gateway &amp; Third-Party Services</strong>
          <ul className="list-disc pl-6 mt-1">
            <li>Donations and purchases on this Platform may be processed via third-party payment gateways such as PhonePe. By initiating a transaction, you agree to the terms and policies of the respective payment gateway providers. We are not liable for any failure or disruption of payment services.</li>
          </ul>
        </li>
        <li>
          <strong>Third Party Links</strong>
          <ul className="list-disc pl-6 mt-1">
            <li>The Platform may contain links to external sites. Such links are provided for convenience only. We do not endorse or have control over the content, policies, or practices of any third-party site.</li>
          </ul>
        </li>
        <li>
          <strong>Indemnification</strong>
          <ul className="list-disc pl-6 mt-1">
            <li>You agree to indemnify and hold harmless WCRT, its officers, directors, volunteers, employees, agents, and partners from any claim, demand, liability, loss, or expense, including reasonable legal fees, arising out of or in connection with your use of the Platform, breach of these terms, or violation of any law or third party right.</li>
          </ul>
        </li>
        <li>
          <strong>Force Majeure</strong>
          <ul className="list-disc pl-6 mt-1">
            <li>Neither party shall be liable for failure to perform any obligation if such failure is due to force majeure, including but not limited to natural disasters, war, civil disturbance, government actions, or any other event beyond reasonable control.</li>
          </ul>
        </li>
        <li>
          <strong>Governing Law and Jurisdiction</strong>
          <ul className="list-disc pl-6 mt-1">
            <li>These terms and conditions shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these terms shall be subject to the exclusive jurisdiction of the courts of New Delhi, India.</li>
          </ul>
        </li>
        <li>
          <strong>Updates and Modifications</strong>
          <ul className="list-disc pl-6 mt-1">
            <li>WCRT reserves the right to modify, amend, or update these terms and conditions at any time without prior notice. It is your responsibility to review these terms periodically for changes.</li>
          </ul>
        </li>
        <li>
          <strong>Contact Information</strong>
          <ul className="list-disc pl-6 mt-1">
            <li>For any concerns, queries, or communication regarding these terms or the Platform, please contact us at:</li>
            <li>Email: <a href="mailto:info@wcrt.in" className="text-blue-700 underline">info@wcrt.in</a></li>
            <li>Registered Office: A-11619, St 44, Gamri, Sombazar, New Delhi, 110053 India</li>
          </ul>
        </li>
      </ol>
    </div>
  );
}
